### ISSUE TITLE
Step-by-Step guide?

### ISSUE THREAD

**Issue by Orku5** [microsoft/Intune-Resource-Access#68]
The whole bloody thing is not working in Visual Studio Code - open the SLN file and what?
When I try to run it, it tells me that it doesn't know the code language despite C# extensions are installed. What the hell do you mean with select build configuration, this does not exist.

Not able import the PS Module either, but if already the first step isn't working.

The only thing, what needs to be done is publishing a bloody certificate to a AzureAD group, but admins now need to piss around and need developer accounts, and all kind of crap - seriously?

Any other MDM solution allows you to import certificates, but not this, no, you need a degree in Visual Studio - no useful documentation on any Microsoft site, and on GitHub it is assumed you know everything....

I have the PFX file, can "install" it manually on the laptop, but can't deploy it using Intune!

**Comment by darba** [comment]
Hi @Orku5,

Sorry for the confustion. 

You will want to use [Visual Studio](https://visualstudio.microsoft.com/vs/) (not Visual Studio Code) to build the project. I believe that since this is an Open Source project, you can use VS Community for free. Check with your company's legal/licensing team.
The PS Module will not import without the project being built. We are actively looking at ways to improve this process.

That being said, can you explain a little more what you are trying to accomplish? The functionality of this code is mostly used to publish certs for use in SMIME scenarios. I'm not sure this applies to your scenario.
